sudo: required
services:
- docker

before_install:
- docker build -t $DOCKER_USERNAME/$DOCKER_IMAGE_NAME -f Dockerfile.dev .

script:
- docker run -e "CI=true" $DOCKER_USERNAME/$DOCKER_IMAGE_NAME npm run test

before_deploy:
- wget -qO- https://toolbelt.heroku.com/install.sh | sh
- echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
- echo $HEROKU_API_KEY | docker login --username $HEROKU_USERNAME --password-stdin  registry.heroku.com
- docker tag $DOCKER_USERNAME/$DOCKER_IMAGE_NAME registry.heroku.com/$HEROKU_APP_NAME/web

deploy:
  provider: script
  script:
    docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:release web --app $HEROKU_APP_NAME
  on:
    branch: master

