sudo: required
services:
  - docker


before_install:
  - docker build -t darvidont/docker-nginx -f Dockerfile.dev .

script:
  - docker run darvidont/docker-nginx npm run test -- --coverage

after_script:
  - docker stop darvidont/docker-nginx